/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Kinopoisk Unofficial API
 * Kinopoisk Unofficial API предоставляет доступ к данным сайта https://www.kinopoisk.ru. Для доступа вы должны получить токен, который будет доступен после регистрации на <a href="https://kinopoiskapiunofficial.tech">https://kinopoiskapiunofficial.tech</a> </br> <b>Ограничения:</b>  лимитов на общее кол-во запросов нет. Но есть на кол-во запросов в секунду. </br> Каждый пользователь имеет ограничение в <b>20 req/sec</b>. </br> <b>Некоторые</b> эндпоинты имеют свои собственные ограничения, они указаны в описании для статуса <b>429</b>. </br>
 * OpenAPI spec version: 2.0.1
 */
import useSwr from 'swr'
import type { SWRConfiguration, Key } from 'swr'
import type { PersonByNameResponse, GetApiV1PersonsParams } from '../../models'
import { customInstance } from '../../mutator/custom-instance'
import type { ErrorType } from '../../mutator/custom-instance'

/**
 * Одна страница может содержать до 50 элементов в items.
 * @summary поиск актеров, режиссеров и т.д. по имени
 */
export const getApiV1Persons = (params: GetApiV1PersonsParams) => {
	return customInstance<PersonByNameResponse>({
		url: `/api/v1/persons`,
		method: 'get',
		params,
	})
}

export const getGetApiV1PersonsKey = (params: GetApiV1PersonsParams) => [
	`/api/v1/persons`,
	...(params ? [params] : []),
]

export type GetApiV1PersonsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1Persons>>
>
export type GetApiV1PersonsQueryError = ErrorType<void>

export const useGetApiV1Persons = <TError = ErrorType<void>>(
	params: GetApiV1PersonsParams,
	options?: {
		swr?: SWRConfiguration<
			Awaited<ReturnType<typeof getApiV1Persons>>,
			TError
		> & { swrKey?: Key; enabled?: boolean }
	}
) => {
	const { swr: swrOptions } = options ?? {}

	const isEnabled = swrOptions?.enabled !== false
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetApiV1PersonsKey(params) : null))
	const swrFn = () => getApiV1Persons(params)

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions
	)

	return {
		swrKey,
		...query,
	}
}
