/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Kinopoisk Unofficial API
 * Kinopoisk Unofficial API предоставляет доступ к данным сайта https://www.kinopoisk.ru. Для доступа вы должны получить токен, который будет доступен после регистрации на <a href="https://kinopoiskapiunofficial.tech">https://kinopoiskapiunofficial.tech</a> </br> <b>Ограничения:</b>  лимитов на общее кол-во запросов нет. Но есть на кол-во запросов в секунду. </br> Каждый пользователь имеет ограничение в <b>20 req/sec</b>. </br> <b>Некоторые</b> эндпоинты имеют свои собственные ограничения, они указаны в описании для статуса <b>429</b>. </br>
 * OpenAPI spec version: 2.0.1
 */
import useSwr from 'swr'
import type { SWRConfiguration, Key } from 'swr'
import type {
	StaffResponse,
	GetApiV1StaffParams,
	PersonResponse,
} from '../../models'
import { customInstance } from '../../mutator/custom-instance'
import type { ErrorType } from '../../mutator/custom-instance'

/**
 * @summary получить данные об актерах, режисерах и т.д. по kinopoisk film id
 */
export const getApiV1Staff = (params: GetApiV1StaffParams) => {
	return customInstance<StaffResponse[]>({
		url: `/api/v1/staff`,
		method: 'get',
		params,
	})
}

export const getGetApiV1StaffKey = (params: GetApiV1StaffParams) => [
	`/api/v1/staff`,
	...(params ? [params] : []),
]

export type GetApiV1StaffQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1Staff>>
>
export type GetApiV1StaffQueryError = ErrorType<void>

export const useGetApiV1Staff = <TError = ErrorType<void>>(
	params: GetApiV1StaffParams,
	options?: {
		swr?: SWRConfiguration<
			Awaited<ReturnType<typeof getApiV1Staff>>,
			TError
		> & { swrKey?: Key; enabled?: boolean }
	}
) => {
	const { swr: swrOptions } = options ?? {}

	const isEnabled = swrOptions?.enabled !== false
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getGetApiV1StaffKey(params) : null))
	const swrFn = () => getApiV1Staff(params)

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions
	)

	return {
		swrKey,
		...query,
	}
}

/**
 * @summary получить данные о конкретном человеке по kinopoisk person id
 */
export const getApiV1StaffId = (id: number) => {
	return customInstance<PersonResponse>({
		url: `/api/v1/staff/${id}`,
		method: 'get',
	})
}

export const getGetApiV1StaffIdKey = (id: number) => [`/api/v1/staff/${id}`]

export type GetApiV1StaffIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1StaffId>>
>
export type GetApiV1StaffIdQueryError = ErrorType<void>

export const useGetApiV1StaffId = <TError = ErrorType<void>>(
	id: number,
	options?: {
		swr?: SWRConfiguration<
			Awaited<ReturnType<typeof getApiV1StaffId>>,
			TError
		> & { swrKey?: Key; enabled?: boolean }
	}
) => {
	const { swr: swrOptions } = options ?? {}

	const isEnabled = swrOptions?.enabled !== false && !!id
	const swrKey =
		swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1StaffIdKey(id) : null))
	const swrFn = () => getApiV1StaffId(id)

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions
	)

	return {
		swrKey,
		...query,
	}
}
