/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Kinopoisk Unofficial API
 * Kinopoisk Unofficial API предоставляет доступ к данным сайта https://www.kinopoisk.ru. Для доступа вы должны получить токен, который будет доступен после регистрации на <a href="https://kinopoiskapiunofficial.tech">https://kinopoiskapiunofficial.tech</a> </br> <b>Ограничения:</b>  лимитов на общее кол-во запросов нет. Но есть на кол-во запросов в секунду. </br> Каждый пользователь имеет ограничение в <b>20 req/sec</b>. </br> <b>Некоторые</b> эндпоинты имеют свои собственные ограничения, они указаны в описании для статуса <b>429</b>. </br>
 * OpenAPI spec version: 2.0.1
 */
import type { FilmProductionStatus } from './filmProductionStatus'
import type { FilmType } from './filmType'
import type { Country } from './country'
import type { Genre } from './genre'

export interface Film {
	kinopoiskId: number
	imdbId: string | null
	nameRu: string | null
	nameEn: string | null
	nameOriginal: string | null
	posterUrl: string
	posterUrlPreview: string
	coverUrl: string | null
	logoUrl: string | null
	reviewsCount: number
	ratingGoodReview: number | null
	ratingGoodReviewVoteCount: number | null
	ratingKinopoisk: number | null
	ratingKinopoiskVoteCount: number | null
	ratingImdb: number | null
	ratingImdbVoteCount: number | null
	ratingFilmCritics: number | null
	ratingFilmCriticsVoteCount: number | null
	ratingAwait: number | null
	ratingAwaitCount: number | null
	ratingRfCritics: number | null
	ratingRfCriticsVoteCount: number | null
	webUrl: string
	year: number | null
	filmLength: number | null
	slogan: string | null
	description: string | null
	shortDescription: string | null
	editorAnnotation: string | null
	isTicketsAvailable: boolean
	productionStatus: FilmProductionStatus
	type: FilmType
	ratingMpaa: string | null
	ratingAgeLimits: string | null
	hasImax: boolean | null
	has3D: boolean | null
	lastSync: string
	countries: Country[]
	genres: Genre[]
	startYear: number | null
	endYear: number | null
	serial?: boolean | null
	shortFilm?: boolean | null
	completed?: boolean | null
}
